### ISSUE TITLE
Server isnt send a object.

### ISSUE THREAD

**Issue by mymek** [takayukii/example-Laravelchat-Echo-Socket.io#2]
Hello, i have problem. After sending a message it isnt showing it at site, just after refresh them, whats the problem? There is a screen from console: http://screenshot.sh/mMHeN3WleuQOH

In attachment is my files of web, its clean site from your GIT. Im trying to do it at Windows 10, can be it a problem?
Thanks a lot for help!

[asdfsa.zip](https://github.com/takayukii/example-Laravelchat-Echo-Socket.io/files/694693/asdfsa.zip)

**Comment by takayukii** [comment]
Hi, I dockerized this repo. Please check readme.md which I newly updated.

**Comment by mymek** [comment]
thanks you very much!

Test broadcast message (php artisan websocket:news hogehoge) 

-> Test broadcast message (docker-compose run app php artisan websocket:news hogehoge)
