### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis:6379]

### ISSUE THREAD

**Issue by pavinthan** [takayukii/example-Laravelchat-Echo-Socket.io#3]
ConnectionException in AbstractConnection.php line 155:
php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis:6379]

**Comment by pavinthan** [comment]
Not respond

**Comment by takayukii** [comment]
I'm totally not sure what you wanted to say by this issue though.., that error may occur when you run this demo without docker.
